[tool.poetry]
name = "stupid-chess-ai"
version = "0.1.0"
description = ""
authors = []
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
chess = "^1.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
